import { Section } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { Demo, SpecRow } from "../_components/demo";
import {
  DurationRace,
  EasingRace,
  ReducedMotionStatus,
} from "../_components/motion-lab";

/** Which step a surface gets, and why. This table is the actual rule. */
const MOTION_ASSIGNMENTS = [
  {
    surface: "Hover, active, focus ring",
    step: "duration-fast",
    why: "The pointer is already there. Anything slower feels like lag rather than feedback.",
  },
  {
    surface: "Checkbox, switch, radio",
    step: "duration-fast",
    why: "A control the finger is on. The tick should land with the click.",
  },
  {
    surface: "Dropdown, select, popover, tooltip",
    step: "duration-fast",
    why: "Opens under the cursor, in place. There is no distance to travel.",
  },
  {
    surface: "Dialog and its overlay",
    step: "duration-normal",
    why: "It interrupts the page, so it earns enough time to be noticed arriving.",
  },
  {
    surface: "Sheet",
    step: "duration-slow",
    why: "The one movement large enough to need it: a whole panel crossing the viewport.",
  },
  {
    surface: "Spinner",
    step: "1.6s, and it survives reduced motion",
    why: "Not decoration. It is the only signal that a request is still in flight.",
  },
];

export function MotionSection() {
  return (
    <div className="flex flex-col" style={{ gap: "var(--section-gap)" }}>
      <Section
        id="motion"
        title="Motion"
        description="Three durations, four curves, and one global reduced-motion rule. Motion here reports what just happened or what is happening now — it is never ornament, and nothing on a PRIME screen moves on its own."
      >
        <div className="flex flex-col gap-5">
          <Demo
            title="The duration scale"
            note="Raced against each other, because nobody can tell 120ms from 200ms in isolation. Press Run."
          >
            <DurationRace />
          </Demo>

          <Demo
            title="The curves"
            note="Enter decelerates into place so the eye can follow it. Exit accelerates away, because once you have dismissed something, watching it leave is dead time. Emphasized overshoots and settles; save it for a deliberate flourish."
          >
            <EasingRace />
          </Demo>

          <div>
            <h4 className="mb-1.5 text-sm font-medium text-foreground">Tokens</h4>
            <SpecRow name="--motion-fast" value="120ms">
              <span className="text-xs text-muted-foreground">
                <code>duration-fast</code> — a state change on something already under
                the cursor
              </span>
            </SpecRow>
            <SpecRow name="--motion-normal" value="200ms">
              <span className="text-xs text-muted-foreground">
                <code>duration-normal</code> — something appearing or disappearing in
                place
              </span>
            </SpecRow>
            <SpecRow name="--motion-slow" value="320ms">
              <span className="text-xs text-muted-foreground">
                <code>duration-slow</code> — something that travels a distance
              </span>
            </SpecRow>
            <SpecRow name="--motion-ease-standard" value="—">
              <span className="text-xs text-muted-foreground">
                <code>ease-standard</code> — the default, and Tailwind&rsquo;s own
              </span>
            </SpecRow>
            <SpecRow name="--motion-ease-enter" value="—">
              <span className="text-xs text-muted-foreground">
                <code>ease-enter</code> — arriving
              </span>
            </SpecRow>
            <SpecRow name="--motion-ease-exit" value="—">
              <span className="text-xs text-muted-foreground">
                <code>ease-exit</code> — leaving
              </span>
            </SpecRow>
            <SpecRow name="--motion-ease-emphasized" value="—">
              <span className="text-xs text-muted-foreground">
                <code>ease-emphasized</code> — overshoots slightly
              </span>
            </SpecRow>
            <p className="mt-2 max-w-prose text-xs text-muted-foreground">
              These are the only two motion namespaces registered with Tailwind, so
              <code className="mx-1">duration-fast</code> and
              <code className="mx-1">ease-enter</code> are generated by the same
              machinery as the core utilities and cooperate with
              <code className="mx-1">transition-*</code> regardless of source order.
              They are also the transition defaults, which is how the transitions
              already written across
              <code className="mx-1">components/ui</code> became token-driven without
              being edited. Never write
              <code className="mx-1">duration-200</code>: an arbitrary number cannot
              follow the token when the scale is re-tuned, which is exactly what went
              wrong with hardcoded pixel type sizes.
            </p>
          </div>
        </div>
      </Section>

      <Section
        id="motion-usage"
        title="Where each step goes"
        description="A duration is a decision about distance and attention, not taste. This table is the rule the components already follow."
      >
        <div className="flex flex-col gap-5">
          <div className="w-full overflow-x-auto">
            <table className="w-full min-w-[36rem] text-left">
              <thead>
                <tr className="hairline-b">
                  <th className="pb-1.5 text-xs font-medium text-muted-foreground">
                    Surface
                  </th>
                  <th className="pb-1.5 text-xs font-medium text-muted-foreground">
                    Step
                  </th>
                  <th className="pb-1.5 text-xs font-medium text-muted-foreground">
                    Why
                  </th>
                </tr>
              </thead>
              <tbody>
                {MOTION_ASSIGNMENTS.map((row) => (
                  <tr key={row.surface} className="hairline-b last:border-b-0">
                    <td className="py-2 pr-3 align-top text-xs text-foreground">
                      {row.surface}
                    </td>
                    <td className="py-2 pr-3 align-top">
                      <code className="text-xs whitespace-nowrap text-foreground">
                        {row.step}
                      </code>
                    </td>
                    <td className="py-2 align-top text-xs text-muted-foreground">
                      {row.why}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <Demo
              title="Interaction feedback"
              note="Hover and hold. The colour transition is fast, and the 1px press travel is what makes a button feel like a button."
            >
              <div className="flex flex-wrap gap-2">
                <Button>Primary</Button>
                <Button variant="outline">Outline</Button>
                <Button variant="secondary">Secondary</Button>
                <Button variant="ghost">Ghost</Button>
              </div>
            </Demo>

            <Demo
              title="A card that is actually clickable"
              note="Elevation, not colour: a card lifts one shadow step on hover. Apply this only when the whole card is a link or a button — a hover effect on a static card promises something that does not happen."
            >
              <a
                href="#motion"
                className="block rounded-lg border border-hairline bg-card p-3 shadow-xs transition-shadow duration-normal hover:shadow-md"
              >
                <p className="text-sm font-medium text-foreground">IT101</p>
                <p className="mt-0.5 text-xs text-muted-foreground">
                  Introduction to Information Technology · 3 semesters
                </p>
              </a>
            </Demo>
          </div>
        </div>
      </Section>

      <Section
        id="reduced-motion"
        title="Reduced motion"
        description="Handled once, globally, in globals.css. A component must never write its own prefers-reduced-motion query — that is how one surface ends up honouring the preference and eleven others quietly ignore it."
      >
        <div className="flex flex-col gap-4">
          <ReducedMotionStatus />

          <div className="grid gap-4 lg:grid-cols-2">
            <Demo title="What the rule does" note="Two details in it are deliberate.">
              <ul className="flex flex-col gap-2 text-xs text-foreground">
                <li>
                  Durations collapse to <code>0.01ms</code>, not to
                  <code className="mx-1">none</code>. An animation that never runs
                  never fires <code>animationend</code>, and Radix waits on that event
                  before unmounting an exiting overlay — so
                  <code className="mx-1">animation: none</code> would leave dismissed
                  dialogs in the DOM.
                </li>
                <li>
                  Anything marked <code>data-motion=&quot;essential&quot;</code> keeps
                  moving. A spinner is the only evidence that a request is still in
                  flight; frozen, it reads as a hung page rather than as a respected
                  preference.
                </li>
              </ul>
            </Demo>

            <Demo
              title="Essential motion"
              note="The spinner inside a pending Button carries the marker. It is the only element in the application that does."
            >
              <div className="flex flex-wrap items-center gap-3">
                <Button loading>Saving…</Button>
                <p className="text-xs text-muted-foreground">
                  Still spinning with reduced motion on, at a slower 1.6s turn.
                </p>
              </div>
            </Demo>
          </div>
        </div>
      </Section>
    </div>
  );
}
